### PR TITLE
Added Foundation (Using npm and grunt tasks)

### PR DESCRIPTION
**Pull request by miniche**
This PR adds Foundation and initialize repository folders and options. The design creation task will come in another PR, when this one will be merged.

### CODE REVIEW

**Comment by miniche** [comment]
`.bowerrc` seems does not to be used by `grunt-bower-task`. Bower components are downloaded into a `lib/`folder.

Todo: find a solution (using another task? using installDir configuration?)

**Comment by miniche** [comment]
@Ninir, Do you have the time to check this PR (and my issue with bower)? :)

**Comment by Ninir** [comment]
@miniche Seems ok for now :)
I fixed the bower stuff for what I understood. Is is better by your side?

**Comment by miniche** [comment]
@Ninir Perfect! Works well.

Are you ready to press to green button? :smile:

**Pull request merged**
